# NumPy

- Standard package for large, multi-dimensional arrays and matrices
- Collection of mathematical functions to efficiently operate on arrays
- Advantages over traditional Python lists

By convention, `numpy` is commonly imported as `np` to make it easier to reference the library's functions and methods.

```python
import numpy as np
```

Here's an example of using `np.zeros` to create a 1-dimensional array of size 5:

```python
import numpy as np

zeros_array = np.zeros(5)
print(zeros_array)  # Output: [0. 0. 0. 0. 0.]
```

Now, let's see an example of using `np.ones` to create a 2-dimensional array of size (3, 2):

```python
ones_array = np.ones((3, 2))
print(ones_array)
```

Output:
```
[[1. 1.]
 [1. 1.]
 [1. 1.]]
```

**Task 0:** Create a NumPy array using `np.zeros` with a shape of (2, 3) and print the resulting array.


## 1. Array Attributes

NumPy arrays have various attributes that provide information about the array:

- `shape`: Tuple indicating the size of each dimension
- `dtype`: Data type of the array elements

Let's see an example of accessing these attributes for a NumPy array:

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # Output: (2, 3)
print(arr.dtype)  # Output: int64
```
#### `np.dtype`

`np.int64` represents signed integer using 64 bits resulting in a large range of -9223372036854775808 to 9223372036854775807. There also exists `np.int32`, `np.int16` and `np.int8` which store integers in less bits resulting in smaller ranges. Analog to that `np.float64`, `np.float32` and `np.float16` define the same structure for floating-point numbers.

**Task 1:** Create a NumPy array with a shape of (1, 2, 3) and dtype `np.int8` using `np.array` and print it.


## 2. Array Indexing

NumPy arrays can be indexed and sliced similar to Python lists.

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[0])    # Output: 1
print(arr[-1])   # Output: 5
print(arr[1:4])  # Output: [2 3 4]
```

For multi-dimensional arrays, indexing and slicing can be done for each dimension separately.

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0, 1])    # Output: 2
print(arr[0, :])    # Output: [1 2 3]
print(arr[:, 1])    # Output: [2 5]
print(arr[0:2, :])  # Output: [[1 2 3]
                    #          [4 5 6]]
```
**Task 2.1:** Which slicing of arr defined above would be printed
```
[[1 2]
 [4 5]]
```

**Task 2.2:** Repeat only using negative slice bounds

## 3. Array Creation

There are several functions like **`np.array()`**, **`np.zeros()`** and **`np.ones()`** for array creation. Here are the most popular ones:

**`np.arange()`** (NumPy version of `range()`)
```python
import numpy as np

arr = np.arange(0, 10, 2)
print(arr)  # Output: [0 2 4 6 8]
```

**`np.linspace()`** (Evenly spaced numbers)
```python
import numpy as np

arr = np.linspace(0, 1, 5)
print(arr)  # Output: [0.   0.25 0.5  0.75 1.  ]
```

**`np.random.rand()`** (Random numbers between 0 and 1)
```python
import numpy as np

arr = np.random.rand(5)
print(arr)  # Output: [0.08, 0.62, 0.64, 0.72, 0.82]
```

**Task 3:** Create a NumPy array containing random values between 0. and 5. with the shape of (2, 4) and print it.

## 4. Array Merging
To merge multiple arrays into one array, the most popular functions are `np.concatenate` and `np.stack`:
```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


print(np.concatenate([a, b]))  # Output: [1 2 3 4 5 6]
print(np.stack([a, b]))        # Output: [[1 2 3]
                               #          [4 5 6]]
```
`np.concatenate` merges along the first existing dimension, while `np.stack` creates a new dimension and merges along this new dimension.

**Task 4.1:** Given the arrays `zeros = np.zeros((3, 3))` and `ones = np.ones((3, 3))` create an array which prints:

```
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
 ```

**Task 4.2:** Given the arrays `zeros = np.zeros((3, 3))` and `ones = np.ones(3, 3)` create an array which prints:

```
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
 ```

**Task 4.3:** Given the arrays `zeros = np.zeros((3, 3))` and `ones = np.ones(3, 3)` create an array which prints:

```
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
 ```

**Task 4.4:** Given the arrays `zeros = np.zeros((3, 3))` and `ones = np.ones(3, 3)` create an array which prints:

```
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
 ```


## 5. Array Operations

NumPy provides various mathematical functions and operations that can be performed on arrays efficiently.

```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


print(a + b)       # Output: [5 7 9]
print(a * b)       # Output: [4 10 18]
print(a < b)       # Output: [True True True]
print(a < 2)       # Output: [True False False]
print(np.sum(a))   # Output: 6
print(np.mean(b))  # Output: 5.0
```

**Task 5.1:** **Without using numpy** write a function which sums all even integers from 0 to 100.


**Task 5.2:** **With using numpy** write a function which sums all even integers from 0 to 100.


**Task 5.3:** Compare the runtime of 5.1 and 5.2.

### Apply along axes

**Task 5.4:** Suppose you have an array with the shape (10, 5) which could be thought of as a table with 10 rows and 5 columns. Write a function which for every row calculates the mean and returns these means as a list. Apply it on `array = np.arange(50).reshape(10, 5)`

**Task 5.5:** Now write a **shorter** function which does the same using the `axis` argument of the `np.mean` function.

Some more numpy functions which are often used are
- `np.random.randn()`: Generates random numbers from a standard normal distribution.
- `np.reshape()`: Changes the shape of an array without changing its data.
- `np.median()`: Computes the median of an array.
- `np.std()`: Computes the standard deviation of an array.
- `np.dot()`: Performs matrix multiplication.
- `np.unique()`: Returns unique elements from an array.
- `np.argsort()`: Returns the indices that would sort an array.

NumPy offers a ton of functions so **before you try to implement a specific function, you should Google if a respective NumPy function exists**.

### Conditional modification

Another very powerful way to indexing besides slicing is shown below:

```python
import numpy as np

arr = np.array([[1, 2, 200], [4, 100, 6]])
over_ten = arr > 10
print(over_ten)  # [[False False  True]
                 # [ False  True  False]]
print(arr[over_ten])  # [200, 100]
```

Here, a boolean array - i.e. array containing True or False values - is created via `over_ten = arr > 10` and then this boolean array is used to index the array.

Using this feature, you can conditonally modify arrays:

```python
import numpy as np

arr = np.array([[1, 2, 200], [4, 100, 6]])
over_ten = arr > 10
arr[over_ten] = 10
print(arr)  # [[1 2 10]
            # [4 10 5]]
```
**Task 5.6:** Threshold the given array `arr = np.array([[.02, .4, 1.1], [.6, .9, .5], [.02, .7, .1]])` such that all values are at least 0.1 and at most 1.

## 6. Infs and NaNs

Consider the following code:

```python
import numpy as np

a = np.array([1, 2, 3])
a = a / 0.
print(a)  # Output: [inf, inf, inf]
a = -1 * a
print(a)  # Output: [-inf, -inf, -inf]
a = a * 0.
print(a)  # Output: [nan, nan, nan]
```
- Dividing by 0 results in `inf` (positive inifinite) values
- Successively multiplying by -1 results in `-inf` (negative inifinite) values
- Successively multiplying by 0 results in `nan` (Not A Number) values

These are the three "nasty" values numpy arrays can consist, as they will likely trigger unwanted behaviour in subsequent code.

`nan` is especially "nasty" as `np.nan == np.nan` is False. Because of that you need `np.isnan` to find `nan` values in an array

```python
import numpy as np

a = np.array([1, 2, np.nan, 4, 5, np.inf])
print(a == np.inf)  # Output: [False, False, False, False, False, True]
print(a == np.nan)  # Output: [False, False, False, False, False, False]
print(np.isnan(a))  # Output: [False, False, True, False, False, False]
```

**Task 6:** Given the array `arr = np.array([1, 2, np.nan, 4, 5, np.nan])` replace all values with the mean of all non-nan values of the array.

## Exercise

1. Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern:
```
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

2. Write a NumPy program to add a border (filled with 0's) around an existing array.

Original array:
```
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
```
Output array:
```
[[ 0. 0. 0. 0. 0.]
...........
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]
```

More exercises: https://www.w3resource.com/python-exercises/numpy/index-array.php